export const FireHouses = [
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '6', label: '6' },
    { value: '7', label: '7' },
    { value: '8', label: '8' },
    { value: '10', label: '10' },
    { value: '12', label: '12' },
    { value: '13', label: '13' },
    { value: '14', label: '14' },
    { value: '15', label: '15' },
    { value: '16', label: '16' },
    { value: '17', label: '17' },
    { value: '18', label: '18' },
    { value: '19', label: '19' },
    { value: '20', label: '20' },
    { value: '22', label: '22' },
    { value: '23', label: '23' },
    { value: '24', label: '24' },
    { value: '26', label: '26' },
    { value: '27', label: '27' },
    { value: '28', label: '28' },
    { value: '29', label: '29' },
    { value: '30', label: '30' },
    { value: '31', label: '31' },
    { value: '32', label: '32' },
    { value: '33', label: '33' },
    { value: '34', label: '34' },
    { value: '35', label: '35' },
    { value: '36', label: '36' },
    { value: '37', label: '37' },
    { value: '38', label: '38' },
    { value: 'Arson', label: 'Arson' },
    { value: 'TA', label: 'TA' },
    { value: 'Fire Boat', label: 'Fire Boat' },
    { value: 'Battalion Chief 1 Bin', label: 'Battalion Chief 1 Bin' },
    { value: 'Battalion Chief 2 Bin', label: 'Battalion Chief 2 Bin' },
    { value: 'Battalion Chief 3 Bin', label: 'Battalion Chief 3 Bin' },
    { value: 'Battalion Chief 4 Bin', label: 'Battalion Chief 4 Bin' },
    { value: 'BC-1', label: 'BC-1' },
    { value: 'BC-2', label: 'BC-2' },
    { value: 'BC-3', label: 'BC-3' },
    { value: 'BC-4', label: 'BC-4' },
    { value: 'DC', label: 'DC' },
]

export const YesNo = [
    { value: true, label: 'Yes' },
    { value: false, label: 'No' },
]

