export const FireHouses = [
  { value: "Firehouse 3", label: "Firehouse 3" },
  { value: "Firehouse 4", label: "Firehouse 4" },
  { value: "Firehouse 6", label: "Firehouse 6" },
  { value: "Firehouse 7", label: "Firehouse 7" },
  { value: "Firehouse 8", label: "Firehouse 8" },
  { value: "Firehouse 10", label: "Firehouse 10" },
  { value: "Firehouse 12", label: "Firehouse 12" },
  { value: "Firehouse 13", label: "Firehouse 13" },
  { value: "Firehouse 14", label: "Firehouse 14" },
  { value: "Firehouse 15", label: "Firehouse 15" },
  { value: "Firehouse 16", label: "Firehouse 16" },
  { value: "Firehouse 17", label: "Firehouse 17" },
  { value: "Firehouse 18", label: "Firehouse 18" },
  { value: "Firehouse 19", label: "Firehouse 19" },
  { value: "Firehouse 20", label: "Firehouse 20" },
  { value: "Firehouse 22", label: "Firehouse 22" },
  { value: "Firehouse 23", label: "Firehouse 23" },
  { value: "Firehouse 24", label: "Firehouse 24" },
  { value: "Firehouse 26", label: "Firehouse 26" },
  { value: "Firehouse 27", label: "Firehouse 27" },
  { value: "Firehouse 28", label: "Firehouse 28" },
  { value: "Firehouse 29", label: "Firehouse 29" },
  { value: "Firehouse 30", label: "Firehouse 30" },
  { value: "Firehouse 31", label: "Firehouse 31" },
  { value: "Firehouse 32", label: "Firehouse 32" },
  { value: "Firehouse 33", label: "Firehouse 33" },
  { value: "Firehouse 34", label: "Firehouse 34" },
  { value: "Firehouse 35", label: "Firehouse 35" },
  { value: "Firehouse 36", label: "Firehouse 36" },
  { value: "Firehouse 37", label: "Firehouse 37" },
  { value: "Firehouse 38", label: "Firehouse 38" },
  { value: "Arson", label: "Arson" },
  { value: "Communications", label: "Communications" },
  { value: "TA", label: "TA" },
  { value: "FB-1", label: "FB-1" },
  { value: "BAT 1", label: "BAT 1" },
  { value: "BAT 1 Bin", label: "BAT 1 Bin" },
  { value: "BAT 2", label: "BAT 2" },
  { value: "BAT 2 Bin", label: "BAT 2 Bin" },
  { value: "BAT 3", label: "BAT 3" },
  { value: "BAT 3 Bin", label: "BAT 3 Bin" },
  { value: "BAT 4", label: "BAT 4" },
  { value: "BAT 4 Bin", label: "BAT 4 Bin" },
  { value: "DEP", label: "DEP" },
  { value: "DEP Bin", label: "DEP Bin" },
  { value: "SCBA", label: "SCBA" }
];

export const YesNo = [
  { value: true, label: "Yes" },
  { value: false, label: "No" }
];
